---
- name: Download Caddy GPG key
  ansible.builtin.get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    dest: /root/caddy-stable.gpg
    mode: "0644"
    checksum: sha256:5791c2fb6b6e82feb5a69834dd2131f4bcc30af0faec37783b2dc1c5c224a82a

- name: Dearmor GPG key
  ansible.builtin.command:
    cmd: gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg /root/caddy-stable.gpg
    creates: /usr/share/keyrings/caddy-stable-archive-keyring.gpg

- name: Add Caddy repository
  ansible.builtin.get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt
    dest: /etc/apt/sources.list.d/caddy-stable.list
    mode: "0644"
    checksum: sha256:b27d8e3f353b8e77214793ab7dfa5111cd502978461c43b4e54e0833ba49e199

- name: Copy Caddyfile template to /etc/caddy
  ansible.builtin.template:
    owner: root
    group: root
    mode: "0644"
    dest: /etc/caddy/Caddyfile
    src: Caddyfile.j2
  notify: Restart Caddy

- name: Install Caddy
  ansible.builtin.apt:
    name: caddy
    state: present
    update_cache: true

- name: Import crowdsec support
  ansible.builtin.include_tasks: crowdsec.yaml
  when: caddy_crowdsec_api_key != ""

- name: Enable caddy service
  ansible.builtin.service:
    name: caddy
    state: started
    enabled: true

- name: Setup Heartbeat Cron for Caddy
  ansible.builtin.cron:
    name: "Caddy Heartbeat"
    # Check local API (Host) -> Ping Pulsetic
    job: "curl -f -s http://127.0.0.1:2019/metrics > /dev/null && curl -fsS -m 5 --retry 3 {{ heartbeat_caddy }} > /dev/null"
    minute: "*/5"
  when: (heartbeat_caddy | default('')) != ""
