container_tsclient_key: ""
tsidp_tskey: ""
syncthing_tskey: ""

borgmatic_ssh_hostname: ""
borgmatic_ssh_username: ""
borgmatic_ssh_password: ""
borgmatic_repository_passphrase: ""
borgmatic_discord_hook: ""

caddy_crowdsec_api_key: ""

ghost_domain_name: ""
ghost_email_user: ""
ghost_email_pass: ""

netdata_discord_alarm_webhook_url: ""

# Token provided by the Forgejo to register runners
# can be shared across all runners and we --name them
# differently based on the inventory hostname
forgejo_runner_token: ""
