container_tsclient_key: ""
tsidp_tskey: ""
syncthing_tskey: ""

borgmatic_ssh_hostname: ""
borgmatic_ssh_username: ""
borgmatic_ssh_password: ""
borgmatic_repository_passphrase: ""
borgmatic_discord_hook: ""

caddy_crowdsec_api_key: ""

ghost_domain_name: ""
ghost_email_user: ""
ghost_email_pass: ""

netdata_discord_alarm_webhook_url: ""

# Set this to 'false' after setting up registration on a node
# See: https://forgejo.org/docs/latest/admin/actions/runner-installation/#standard-registration
forgejo_needs_registration: true
