---
- name: Create /srv/cupdate
  ansible.builtin.file:
    owner: root
    group: root
    mode: "0755"
    state: directory
    path: /srv/cupdate

- name: Copy docker-compose files to /srv/cupdate
  ansible.builtin.copy:
    owner: root
    group: root
    mode: "0644"
    dest: /srv/cupdate/docker-compose.yml
    src: docker-compose.yml
  notify: Restart Cupdate

- name: Enable Cupdate docker
  community.docker.docker_compose_v2:
    project_src: /srv/cupdate
    wait: true
    wait_timeout: 90
