---
- name: Create docker-compose directory for portainer
  ansible.builtin.file:
    owner: root
    group: root
    mode: "0755"
    state: directory
    path: /srv/portainer

- name: Copy docker-compose files to /srv/portainer
  ansible.builtin.template:
    owner: root
    group: root
    mode: "0644"
    dest: /srv/portainer/docker-compose.yml
    src: docker-compose.yml.j2
  notify: Restart Portainer

- name: Enable portainer docker
  community.docker.docker_compose_v2:
    project_src: /srv/portainer
    build: never
