---
- name: Install UFW
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- name: Allow all access to tcp port 80
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp
    comment: "Incoming HTTP requests"

- name: Allow all access to tcp port 443
  community.general.ufw:
    rule: allow
    port: 443
    proto: tcp
    comment: "Incoming HTTPS requests"

- name: Allow all access from RFC1918 networks to this host
  community.general.ufw:
    rule: allow
    src: "{{ item }}"
    comment: "Internal networking between docker"
  loop:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16

- name: Allow any access on the interface tailscale0
  community.general.ufw:
    rule: allow
    interface_in: tailscale0
    comment: "Tailscale is fully trusted"

- name: Enable UFW
  community.general.ufw:
    state: enabled
    logging: "on"
